trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build MacOS app
    pool:
      vmImage: 'macOS-latest'
    continueOnError: false
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        make package
      displayName: 'Build'

    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'GitHubReleaseConnection'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        assets: '$(System.DefaultWorkingDirectory)/out/**/*.zip'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'

  - job: Build Win app
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run make
      displayName: 'Build'

    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'GitHubReleaseConnection'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        assets: '$(System.DefaultWorkingDirectory)/out/**/*.zip'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'
